project:
  type: website
  output-dir: docs

website:
  title: "Sofie Flom"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: About.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: jewelry.qmd
        text: Jewelry! 
      - resume.qmd

format:
  html:
    theme: 
      - sketchy
      - styles.scss
    toc: true

about: jolla