project:
  type: website
  output-dir: docs

website:
  title: "Sofie Flom"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - About.qmd
      - projects.qmd
      - jewelry.qmd
      - resume.qmd

format:
  html:
    theme: default
    toc: true

about: jolla